### ISSUE TITLE
Template for project web page

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde.github.io#3]
We need to have Jekyll template for project pages published on each project's `gh-pages` branch. This template should follow the same visual style, but also include new project-specific features (e.g. download buttons, syncing with the repo, online documentation, etc...). A good candidate to start experimenting with is [forsyde-shallow](https://github.com/forsyde/forsyde-shallow)

**Comment by Rojods** [comment]
This needs to be moved into the "README" and instructions of every other project, rather than staying here, i'd say.

**Comment by ugeorge** [comment]
I believe this ended up in the `forsyde-web-theme` repo, which was not there before, but I forgot to close the issue.
