### ISSUE TITLE
Migrate Jekyll template to own repo

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde.github.io#4]
As per [this site](https://www.siteleaf.com/blog/remote-themes/), GitHub pages support templates hosted on remote repos. The current development of the site at [forsyde.github.io](forsyde.github.io) is not sustainable, as it is based on local templates + content + update hacks for each project page. We need to migrate the ForSyDe web theme to a new repository which will be imported by each project with minimal modifications, ideally at `forsyde/forsyde-web-theme`.

**Comment by ingo-sander** [comment]
Do you want my OK? Just go ahead with your suggestions!
